feat: add some initial cargo-fuzz test for queues
tweedegolf/sequential-storage pull request #13
Opened 2023-12-20 15:20 UTC by lulf

I played with using cargo-fuzz for testing the queue behavior. I wanted to reuse the mock flash for that, but that would require gating it behind some hidden feature, not sure if you have a preferred way.

2023-12-20 15:30 UTC, Dirbaio commented on fuzz/fuzz_targets/queue.rs
> +                    .unwrap();
if this unwrap is never firing, it means the fuzzer is never getting to fill up the flash, which is something that would be interesting to test. Maybe make the flash smaller?

2023-12-20 15:30 UTC, Dirbaio commented on fuzz/fuzz_targets/queue.rs
> +                    .is_some());
should assert the data came out fine too

2023-12-20 18:29 UTC, diondokter commented
Hmmm, cool!
Dario's suggestions are good.

Also, seems like the fuzz target folder is not gitignored

2023-12-20 18:50 UTC, diondokter commented on fuzz/fuzz_targets/queue.rs
> +                    .is_some());
Yeah and adding peek as an operation would be good too.
Probably best to keep track of all the data that is pushed so it can be checked when peeking and popping.

2023-12-20 19:01 UTC, diondokter commented on fuzz/fuzz_targets/queue.rs
> +    Pop,
Given a distribution of random values, this will result in **way** more pops than pushes. I guess the fuzzer should  be able to figure it out, but is this as efficient as can be? Is it useful to be able to push many in one op?

I don't know... Maybe that's not relevant at all

2023-12-20 19:13 UTC, lulf commented on fuzz/fuzz_targets/queue.rs
> +    Pop,
Yeah... I need to play more with this check if there's an elegant way to control the distribution

2023-12-20 19:16 UTC, lulf commented on fuzz/fuzz_targets/queue.rs
> +                    .is_some());
Yeah, I had a naive map initially, but because the same value could be push multiple times, it would need to track which push put which data in there. Doable of course, but a bit more work so I'll add that next.

2023-12-21 10:42 UTC, lulf commented
@diondokter I'm trying to have the fuzzer determine whether or not a push() operation should fail due to out of capacity, and for that I need to calculate the expected overhead of the metadata.

From what I can infer, the per-item overhead is 6 bytes, but aligned to word boundary, and at the start(?) of each page there is a byte controlling which state the page is in?

2023-12-21 11:01 UTC, diondokter commented
> From what I can infer, the per-item overhead is 6 bytes, but aligned to word boundary, and at the start(?) of each page there is a byte controlling which state the page is in?

1. There's two words that control the page state. The first and the last word. So the total space in a page is the page - 2 words
2. An item must fully fit on one page, they cannot be split over two pages. When an item doesn't fit in the remaining space of a page, the page is closed and the next page is used to write the item into.
3. The layout of an item is documented here: https://github.com/tweedegolf/sequential-storage/blob/9ffb7b6453cf7d6b19b7baba92e79009c2cacf9f/src/item.rs#L1-L20
  There's this helper function too: https://github.com/tweedegolf/sequential-storage/blob/9ffb7b6453cf7d6b19b7baba92e79009c2cacf9f/src/item.rs#L152
  Just give it the space left in the page and it'll tell you how much data can still be stored in the page. It's None if no data can be stored anymore.

2023-12-21 16:03 UTC, lulf commented
@diondokter believe it has found one off-by-one bug in next_free_item (but please check it, see https://github.com/tweedegolf/sequential-storage/pull/13/commits/a5217501bf654f06e7303b1ea806e509f703a7b4).

Another fuzz test to add (which I'd like to add in a follow-up PR) is to take an existing 'image' that may be corrupted in random ways and see what happens.

Regarding the distribution, we can do that by using a custom type and implementing the Arbitrary trait. However, I think what's there is pretty good already.

Finally, there is a question of semantics and another potential bug. At the moment a push of an empty item will fail with StorageFull in some cases, and some cases not (depending on what happened before). I'd like to get your view on what the behavior should be if there is space for the aligned header but not the empty item. My thinking is that it should be allowed (could be useful as some kind of external marker?)

2023-12-21 16:11 UTC, diondokter commented
Nice! I'll review later.

As for the 0 length, that is allowed. It didn't use to, so the weird behavior might be from that still. So yeah, I do consider that a bug

2023-12-21 17:39 UTC, lulf commented
@diondokter Just a quick update, fixed a bug in the new find_max_fit() handling 0 length correctly.

2023-12-21 19:06 UTC, diondokter requested changes
Alright, looks pretty good! Only a couple of small things.

2023-12-21 19:06 UTC, diondokter commented on src/item.rs
> +                    > end_address
Ah, yeah this is easy to get wrong. I was just about to write this fix is wrong, but it is correct.
`end_address` is exclusive, but so is the value we calculate. This means that if they're equal, it's still fine.
Well spotted!

2023-12-21 19:34 UTC, lulf commented on src/item.rs
> +                    > end_address
Thanks for having a look, I was really not sure about this myself :D

2023-12-21 19:34 UTC, lulf commented on .vscode/settings.json
Thanks!

2023-12-21 19:43 UTC, lulf commented on src/queue.rs
> +pub fn find_max_fit<S: NorFlash>(
Looking back at this now, it started as a utility in my test to verify the behaviour of the queue. But now that it's part of the queue implementation itself, it also feels weird to use it in a test 😆

2023-12-21 19:57 UTC, diondokter commented
Btw, I just added a simple CI script on master.
We could add a small fuzz step that fuzzes for only like 10 seconds.

Not sure how much that would bring us, but at least the fuzzer would run every change, even if it's brief.

For statime we do that (though that still uses the old actions-rs): https://github.com/pendulum-project/statime/blob/main/.github/workflows/rust.yml#L101-L124

2023-12-21 20:19 UTC, diondokter approved these changes
Thanks a bunch!

2023-12-21 20:19 UTC, merged