WIP: Async support
tweedegolf/sequential-storage pull request #17
Opened 2024-01-02 14:42 UTC by lulf

@diondokter Just a headsup that I started looking at this... I've gotten the queue implementation to work nicely with async, and was able to use it with the Flash on nrf-softdevice. This revealed an issue which might be only specific to the softdevice, where the buffer to write into flash must be word-aligned, so the AlignedBuf is introduced for that. I set the alignment to 32 bytes, but I'm not sure if there are anyone besides the nRF flash which has this requirement (could be set to 4 bytes in that case).

I need to finish the map support, but just thought to give an early notice!

2024-01-02 15:45 UTC, diondokter commented
Nice! I have just merged something big, so you're now getting conflicts :P
But I don't have anything in the pipeline right now, so after resolving this you should be clear.

2024-01-02 15:54 UTC, diondokter commented on src/lib.rs
> +struct AlignedBuf([u8; MAX_WORD_SIZE]);
32 is a bit much I think. If nordic needs 4, then I'm ok with that. Just make it 4 then.
```suggestion
#[repr(align(4))]
struct AlignedBuf([u8; MAX_WORD_SIZE]);
```

2024-01-02 15:54 UTC, diondokter commented on fuzz/fuzz_targets/queue.rs
> +struct AlignedBuf([u8; MAX_VALUE_SIZE + 1]);
I don't see why we need this in the fuzzer.

2024-01-02 15:54 UTC, diondokter commented on src/item.rs
> +pub async fn find_next_free_item_spot<S: NorFlash>(
Just a note that the recent merge changed this function. So this has to be revisited

2024-01-02 15:54 UTC, diondokter commented on src/item.rs
> +pub struct ItemIter {
The item and item header iteration functions had some changes in the recent merge. So make sure to revisit the code in this

2024-01-02 15:54 UTC, diondokter commented on src/lib.rs
> -    fn test_find_pages() {
I would still like this test to exist.
I don't mind having a dependency on tokio-test to make it work.

2024-01-02 15:55 UTC, diondokter commented
Map is going to be annoying though because it uses a bit of recursion for its store operation. This can't be done with futures without alloc. So that has to be changed to a loop...

2024-01-02 17:11 UTC, lulf commented on fuzz/fuzz_targets/queue.rs
> +struct AlignedBuf([u8; MAX_VALUE_SIZE + 1]);
Primarily because I added a check in the mock flash to check the buffer alignment, and the fuzzer would trigger this condition unless it provided an aligned buffer for writing.

2024-01-03 11:58 UTC, lulf commented
Map support is done now. Tested queue on nRF with nrf-softdevice and qspi flash.

2024-01-03 16:04 UTC, lulf commented
> @lulf Thanks!
> 
> Took a quick look and looks good at first glance. Need to spend more time to do a thorough review.
> 

No rush on my part, thanks for taking the time.

> I'm not really feeling the required input buffer alignment for the mock flash, though. The embedded-storage traits don't require it and if the nordic implementation does, then that's more strict than is allowed from the traits. I'm willing to make it work for it, for example by using the aligned buffer you made. But I don't want it to become annoying and having to use a new `write_aligned` function makes it more annoying.
> 

We can remove the alignment requirement from the mock flash, it was merely added to trigger this condition in tests and in the fuzzer, otherwise it might sneak in a bug in the future and break nrf flash in the process, so I figured it would be useful for preventing a regression in the future. The write_aligned was added so that the unit test in lib.rs didn't have to do the alignment dance, I'm happy to move that into the test instead.

The important part is that the internal buffers in sequential-storage used to write things like item headers are aligned, otherwise it simply won't work with that nrf flash alignment. 

> Or are there more flash implementations that require the write buffer to be aligned?

No that I'm aware of, it's an nRF quirk, might even be specific to softdevice.

2024-01-06 21:11 UTC, diondokter requested changes
Thorough review done. Couple of things that I'd like to see different

2024-01-06 21:11 UTC, diondokter commented on src/item.rs
> +    /// If the end of the headers is reached, a `None` item header is returned.
This is a bit vague. What does 'until the callback determines the next element.' mean?

State what the function does when the callback returns break/false. Which item is returned? What is the next item that this iterator will yield?

2024-01-06 21:11 UTC, diondokter commented on src/item.rs
> +        }
Either we check this every loop iteration or we fully rely on the `ItemHeader::read_new` function to do this check.

(I'd say do the latter and just remove this check)

2024-01-06 21:11 UTC, diondokter commented on src/item.rs
> +                    self.current_address += S::WORD_SIZE as u32;
This branch was changed in #16 

```suggestion
                    self.current_address = ItemHeader::data_address::<S>(self.current_address);
```

2024-01-06 21:12 UTC, diondokter commented on fuzz/fuzz_targets/map.rs
>                          &mut buf,
Whoops, meant to put this on the `&buf` line here

2024-01-06 21:13 UTC, diondokter commented on src/lib.rs
> +struct AlignedBuf([u8; MAX_WORD_SIZE]);
Ok, maybe generic T is a bit much...

2024-01-07 17:08 UTC, lulf commented on src/map.rs
> +//!     block_on(fetch_item::<MyCustomType, _>(
I'm not sure exactly what you mean by that. Something like this?

```
block_on(async {
    fetch_item::<MyCustomType, _>().await
})
```

Or

```
async {
    fetch_item::<MyCustomType, _>().await
}
```


Or without the `block_on` completely? Both will compile, but without anything polling the async block, perhaps users will be surprised their code doesn't run. Adding .await to the async block will not work for doc comments, not sure if there is a workaround for it?

2024-01-07 17:08 UTC, lulf commented on src/map.rs
>          let mut data_buffer = [0; 128];
Yes, you're probably right. Could be in most cases it will be aligned and we're just lucky.

2024-01-07 17:10 UTC, lulf commented on src/map.rs
> +//!     block_on(fetch_item::<MyCustomType, _>(
Or do you mean wrap the entire doc comment in a 

```
block_on(async {
    ....
})
```

2024-01-07 19:40 UTC, diondokter commented on src/map.rs
> +//!     block_on(fetch_item::<MyCustomType, _>(
This last one yeah

2024-01-08 07:58 UTC, lulf commented on src/item.rs
> +        callback: impl Fn(&ItemHeader, u32) -> ControlFlow<(), ()>,
IMHO I think using an enum (doesn't need to be controlflow) reads a lot better, because you see the intention of 'break the loop' or 'continue' a lot clearer than from reading true, false.

2024-01-08 08:15 UTC, lulf commented
@diondokter Thanks for the review! All comments should be addressed, except the bool one... I can change it to bool if you insist, but I really do think it hurts readability.

2024-01-08 08:23 UTC, diondokter commented on src/item.rs
> +        callback: impl Fn(&ItemHeader, u32) -> ControlFlow<(), ()>,
In my eyes this function is a lot like `take_while` which does take a bool: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.take_while.

I do agree that at least in theory the enum is nicer, in practice I think a bool is much nicer.
Also, ControlFlow has many useful apis still behind a feature flag.

2024-01-08 09:18 UTC, lulf commented on src/item.rs
> +        callback: impl Fn(&ItemHeader, u32) -> ControlFlow<(), ()>,
Removed control flow now.

2024-01-10 09:39 UTC, diondokter commented
Awesome, thanks for the work!

2024-01-10 09:39 UTC, merged