Add `map::Value` imps for `bool` and `Option<T>`
tweedegolf/sequential-storage pull request #64
Opened 2024-08-04 12:27 UTC by korken89

Added some more `Value` impls to reduce the needed boilerplate in users' crates.

2024-08-04 12:44 UTC, diondokter requested changes
Cool, thanks! One thing and it's ready for merge

2024-08-04 12:44 UTC, diondokter commented on src/map.rs
> +            <u8 as Value>::serialize_into(&1, buffer)?;
Maybe make this the fancy newfangled bool?

2024-08-04 17:50 UTC, korken89 commented on src/map.rs
> +            <u8 as Value>::serialize_into(&1, buffer)?;
Updated!

2024-08-04 18:45 UTC, korken89 commented
I also added an implementation for arrays.

2024-08-04 20:37 UTC, diondokter commented
Alright, looks nice!

I almost thought impl'in the trait for bool would be a breaking change. But luckily it's not! Since bool is never a user-defined type and they couldn't have implemented it themselves.

2024-08-04 20:38 UTC, diondokter commented
Oh! We now get that error in CI!

Weird! Maybe a different CI machine with an updated linker or something?
No idea. I'll merge anyways an submit an issue to figure it out.

2024-08-04 20:53 UTC, diondokter commented
Ah! Actually these errors do need looking at.

See, your changes to the Value impls changes the way the type inference is done which messes up the tests.
And if it messes up the tests, then probably also user code, which would make this a breaking change.
I think a breaking change is fine for this, because it's better. But the tests do need to be fixed.

2024-08-04 20:54 UTC, korken89 commented
I'll fix the tests first thing in the morning! 🚀

2024-08-05 06:21 UTC, korken89 commented
I have update the tests and fixed the impl! 
It's a bit unfortunate that I cannot get the type inference to work the same which makes it into a breaking change. :disappointed:

2024-08-05 07:51 UTC, diondokter commented
Thanks!

2024-08-05 07:51 UTC, merged